import { Destination } from "../types/common";

export const HOME_AIRPORT = "TLV";

export const DESTINATIONS: Destination[] = [
  {
    id: "paris",
    city: "פריז",
    cityEn: "Paris",
    country: "צרפת",
    airportCode: "CDG",
    imageUrl: "https://picsum.photos/seed/paris-travel/800/600",
    popular: true,
    description: "עיר האורות - מגדל אייפל, לובר ורומנטיקה בכל פינה",
  },
  {
    id: "rome",
    city: "רומא",
    cityEn: "Rome",
    country: "איטליה",
    airportCode: "FCO",
    imageUrl: "https://picsum.photos/seed/rome-travel/800/600",
    popular: true,
    description: "היסטוריה עתיקה, פסטה איטלקית וקולוסיאום מרהיב",
  },
  {
    id: "barcelona",
    city: "ברצלונה",
    cityEn: "Barcelona",
    country: "ספרד",
    airportCode: "BCN",
    imageUrl: "https://picsum.photos/seed/barcelona-travel/800/600",
    popular: true,
    description: "אדריכלות גאודי, חופים ואווירה תוססת",
  },
  {
    id: "london",
    city: "לונדון",
    cityEn: "London",
    country: "אנגליה",
    airportCode: "LHR",
    imageUrl: "https://picsum.photos/seed/london-travel/800/600",
    popular: true,
    description: "בירת בריטניה - מוזיאונים, קניות ותרבות",
  },
  {
    id: "athens",
    city: "אתונה",
    cityEn: "Athens",
    country: "יוון",
    airportCode: "ATH",
    imageUrl: "https://picsum.photos/seed/athens-travel/800/600",
    popular: true,
    description: "האקרופוליס, האיים היווניים ומטבח ים תיכוני",
  },
  {
    id: "larnaca",
    city: "לרנקה",
    cityEn: "Larnaca",
    country: "קפריסין",
    airportCode: "LCA",
    imageUrl: "https://picsum.photos/seed/larnaca-travel/800/600",
    popular: true,
    description: "חופשה קרובה ונוחה עם חופים יפים",
  },
  {
    id: "istanbul",
    city: "איסטנבול",
    cityEn: "Istanbul",
    country: "טורקיה",
    airportCode: "IST",
    imageUrl: "https://picsum.photos/seed/istanbul-travel/800/600",
    popular: true,
    description: "שוק תבלינים, מסגד הסולטן אחמד ותרבות עשירה",
  },
  {
    id: "bangkok",
    city: "בנגקוק",
    cityEn: "Bangkok",
    country: "תאילנד",
    airportCode: "BKK",
    imageUrl: "https://picsum.photos/seed/bangkok-travel/800/600",
    popular: true,
    description: "מקדשים, שווקים צפים ואוכל רחוב מהמם",
  },
  {
    id: "amsterdam",
    city: "אמסטרדם",
    cityEn: "Amsterdam",
    country: "הולנד",
    airportCode: "AMS",
    imageUrl: "https://picsum.photos/seed/amsterdam-travel/800/600",
    popular: true,
    description: "תעלות, אופניים ומוזיאונים עולמיים",
  },
  {
    id: "new-york",
    city: "ניו יורק",
    cityEn: "New York",
    country: "ארה\"ב",
    airportCode: "JFK",
    imageUrl: "https://picsum.photos/seed/newyork-travel/800/600",
    popular: true,
    description: "העיר שלא ישנה לעולם - קניות, ברודוויי וגורדי שחקים",
  },
  {
    id: "budapest",
    city: "בודפשט",
    cityEn: "Budapest",
    country: "הונגריה",
    airportCode: "BUD",
    imageUrl: "https://picsum.photos/seed/budapest-travel/800/600",
    popular: false,
    description: "מרחצאות תרמיים ואדריכלות מרהיבה על נהר הדנובה",
  },
  {
    id: "prague",
    city: "פראג",
    cityEn: "Prague",
    country: "צ'כיה",
    airportCode: "PRG",
    imageUrl: "https://picsum.photos/seed/prague-travel/800/600",
    popular: false,
    description: "עיר מאה המגדלים עם רחובות אבן ציוריים",
  },
  {
    id: "vienna",
    city: "וינה",
    cityEn: "Vienna",
    country: "אוסטריה",
    airportCode: "VIE",
    imageUrl: "https://picsum.photos/seed/vienna-travel/800/600",
    popular: false,
    description: "ארמונות קיסריים, קפה וינאי ומוזיקה קלאסית",
  },
  {
    id: "dubai",
    city: "דובאי",
    cityEn: "Dubai",
    country: "איחוד האמירויות",
    airportCode: "DXB",
    imageUrl: "https://picsum.photos/seed/dubai-travel/800/600",
    popular: true,
    description: "מגדלים מפוארים, קניונים ומדבר עוצר נשימה",
  },
  {
    id: "milan",
    city: "מילאנו",
    cityEn: "Milan",
    country: "איטליה",
    airportCode: "MXP",
    imageUrl: "https://picsum.photos/seed/milan-travel/800/600",
    popular: false,
    description: "בירת האופנה עם קתדרלה מרשימה ואופרה",
  },
];

// Domestic (Israel) destinations for hotel-only search
export const DOMESTIC_DESTINATIONS: Destination[] = [
  {
    id: "eilat",
    city: "אילת",
    cityEn: "Eilat",
    country: "ישראל",
    airportCode: "ETM",
    imageUrl: "https://picsum.photos/seed/eilat-travel/800/600",
    popular: true,
    description: "ים סוף, שמש כל השנה ומלונות יוקרה",
  },
  {
    id: "tiberias",
    city: "טבריה",
    cityEn: "Tiberias",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/tiberias-travel/800/600",
    popular: true,
    description: "כנרת, ספא ונופש רגוע בצפון",
  },
  {
    id: "dead-sea",
    city: "ים המלח",
    cityEn: "Dead Sea",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/deadsea-travel/800/600",
    popular: true,
    description: "מרחצאות מינרלים ומלונות ספא ברמה עולמית",
  },
  {
    id: "tel-aviv",
    city: "תל אביב",
    cityEn: "Tel Aviv",
    country: "ישראל",
    airportCode: "TLV",
    imageUrl: "https://picsum.photos/seed/telaviv-travel/800/600",
    popular: true,
    description: "חופים, חיי לילה ומסעדות ברמה עולמית",
  },
  {
    id: "jerusalem",
    city: "ירושלים",
    cityEn: "Jerusalem",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/jerusalem-travel/800/600",
    popular: false,
    description: "העיר העתיקה וההיסטוריה בת אלפי השנים",
  },
];

export const ALL_DESTINATIONS = [...DESTINATIONS, ...DOMESTIC_DESTINATIONS];

// English city name for a given IATA code, used for real booking-site deep links.
export function airportCityEn(code: string): string {
  if (code === HOME_AIRPORT) return "Tel Aviv";
  const dest = ALL_DESTINATIONS.find((d) => d.airportCode === code);
  return dest?.cityEn ?? code;
}

export const AIRLINES: { code: string; name: string }[] = [
  { code: "LY", name: "אל על" },
  { code: "IZ", name: "ארקיע" },
  { code: "6H", name: "ישראייר" },
  { code: "W6", name: "וויזאייר" },
  { code: "FR", name: "ראיינאייר" },
  { code: "TK", name: "טורקיש איירליינס" },
  { code: "LH", name: "לופטהנזה" },
  { code: "AF", name: "אייר פראנס" },
  { code: "BA", name: "בריטיש איירווייז" },
  { code: "EK", name: "אמירייטס" },
];
