import { Destination } from "../types/common";

export const HOME_AIRPORT = "TLV";

export const DESTINATIONS: Destination[] = [
  {
    id: "paris",
    city: "פריז",
    cityEn: "Paris",
    country: "צרפת",
    airportCode: "CDG",
    imageUrl: "https://picsum.photos/seed/paris-travel/800/600",
    popular: true,
    description: "עיר האורות - מגדל אייפל, לובר ורומנטיקה בכל פינה",
  },
  {
    id: "rome",
    city: "רומא",
    cityEn: "Rome",
    country: "איטליה",
    airportCode: "FCO",
    imageUrl: "https://picsum.photos/seed/rome-travel/800/600",
    popular: true,
    description: "היסטוריה עתיקה, פסטה איטלקית וקולוסיאום מרהיב",
  },
  {
    id: "barcelona",
    city: "ברצלונה",
    cityEn: "Barcelona",
    country: "ספרד",
    airportCode: "BCN",
    imageUrl: "https://picsum.photos/seed/barcelona-travel/800/600",
    popular: true,
    description: "אדריכלות גאודי, חופים ואווירה תוססת",
  },
  {
    id: "london",
    city: "לונדון",
    cityEn: "London",
    country: "אנגליה",
    airportCode: "LHR",
    imageUrl: "https://picsum.photos/seed/london-travel/800/600",
    popular: true,
    description: "בירת בריטניה - מוזיאונים, קניות ותרבות",
  },
  {
    id: "athens",
    city: "אתונה",
    cityEn: "Athens",
    country: "יוון",
    airportCode: "ATH",
    imageUrl: "https://picsum.photos/seed/athens-travel/800/600",
    popular: true,
    description: "האקרופוליס, האיים היווניים ומטבח ים תיכוני",
  },
  {
    id: "larnaca",
    city: "לרנקה",
    cityEn: "Larnaca",
    country: "קפריסין",
    airportCode: "LCA",
    imageUrl: "https://picsum.photos/seed/larnaca-travel/800/600",
    popular: true,
    description: "חופשה קרובה ונוחה עם חופים יפים",
  },
  {
    id: "istanbul",
    city: "איסטנבול",
    cityEn: "Istanbul",
    country: "טורקיה",
    airportCode: "IST",
    imageUrl: "https://picsum.photos/seed/istanbul-travel/800/600",
    popular: true,
    description: "שוק תבלינים, מסגד הסולטן אחמד ותרבות עשירה",
  },
  {
    id: "bangkok",
    city: "בנגקוק",
    cityEn: "Bangkok",
    country: "תאילנד",
    airportCode: "BKK",
    imageUrl: "https://picsum.photos/seed/bangkok-travel/800/600",
    popular: true,
    description: "מקדשים, שווקים צפים ואוכל רחוב מהמם",
  },
  {
    id: "amsterdam",
    city: "אמסטרדם",
    cityEn: "Amsterdam",
    country: "הולנד",
    airportCode: "AMS",
    imageUrl: "https://picsum.photos/seed/amsterdam-travel/800/600",
    popular: true,
    description: "תעלות, אופניים ומוזיאונים עולמיים",
  },
  {
    id: "new-york",
    city: "ניו יורק",
    cityEn: "New York",
    country: "ארה\"ב",
    airportCode: "JFK",
    imageUrl: "https://picsum.photos/seed/newyork-travel/800/600",
    popular: true,
    description: "העיר שלא ישנה לעולם - קניות, ברודוויי וגורדי שחקים",
  },
  {
    id: "budapest",
    city: "בודפשט",
    cityEn: "Budapest",
    country: "הונגריה",
    airportCode: "BUD",
    imageUrl: "https://picsum.photos/seed/budapest-travel/800/600",
    popular: false,
    description: "מרחצאות תרמיים ואדריכלות מרהיבה על נהר הדנובה",
  },
  {
    id: "prague",
    city: "פראג",
    cityEn: "Prague",
    country: "צ'כיה",
    airportCode: "PRG",
    imageUrl: "https://picsum.photos/seed/prague-travel/800/600",
    popular: false,
    description: "עיר מאה המגדלים עם רחובות אבן ציוריים",
  },
  {
    id: "vienna",
    city: "וינה",
    cityEn: "Vienna",
    country: "אוסטריה",
    airportCode: "VIE",
    imageUrl: "https://picsum.photos/seed/vienna-travel/800/600",
    popular: false,
    description: "ארמונות קיסריים, קפה וינאי ומוזיקה קלאסית",
  },
  {
    id: "dubai",
    city: "דובאי",
    cityEn: "Dubai",
    country: "איחוד האמירויות",
    airportCode: "DXB",
    imageUrl: "https://picsum.photos/seed/dubai-travel/800/600",
    popular: true,
    description: "מגדלים מפוארים, קניונים ומדבר עוצר נשימה",
  },
  {
    id: "milan",
    city: "מילאנו",
    cityEn: "Milan",
    country: "איטליה",
    airportCode: "MXP",
    imageUrl: "https://picsum.photos/seed/milan-travel/800/600",
    popular: false,
    description: "בירת האופנה עם קתדרלה מרשימה ואופרה",
  },
  {
    id: "madrid",
    city: "מדריד",
    cityEn: "Madrid",
    country: "ספרד",
    airportCode: "MAD",
    imageUrl: "https://picsum.photos/seed/madrid-travel/800/600",
    popular: true,
    description: "ארמון המלוכה, מוזיאון פראדו וחיי לילה תוססים",
  },
  {
    id: "lisbon",
    city: "ליסבון",
    cityEn: "Lisbon",
    country: "פורטוגל",
    airportCode: "LIS",
    imageUrl: "https://picsum.photos/seed/lisbon-travel/800/600",
    popular: true,
    description: "רחובות מרוצפים, חשמליות צהובות ופאדו",
  },
  {
    id: "berlin",
    city: "ברלין",
    cityEn: "Berlin",
    country: "גרמניה",
    airportCode: "BER",
    imageUrl: "https://picsum.photos/seed/berlin-travel/800/600",
    popular: true,
    description: "היסטוריה מודרנית, אמנות רחוב וחיי לילה",
  },
  {
    id: "munich",
    city: "מינכן",
    cityEn: "Munich",
    country: "גרמניה",
    airportCode: "MUC",
    imageUrl: "https://picsum.photos/seed/munich-travel/800/600",
    popular: false,
    description: "בירת בוואריה - בירה, אדריכלות וכיכר מרינפלאץ",
  },
  {
    id: "frankfurt",
    city: "פרנקפורט",
    cityEn: "Frankfurt",
    country: "גרמניה",
    airportCode: "FRA",
    imageUrl: "https://picsum.photos/seed/frankfurt-travel/800/600",
    popular: false,
    description: "מרכז פיננסי אירופי עם עיר עתיקה קסומה",
  },
  {
    id: "zurich",
    city: "ציריך",
    cityEn: "Zurich",
    country: "שוויץ",
    airportCode: "ZRH",
    imageUrl: "https://picsum.photos/seed/zurich-travel/800/600",
    popular: false,
    description: "אגם, אלפים ואיכות חיים ברמה עולמית",
  },
  {
    id: "geneva",
    city: "ז'נבה",
    cityEn: "Geneva",
    country: "שוויץ",
    airportCode: "GVA",
    imageUrl: "https://picsum.photos/seed/geneva-travel/800/600",
    popular: false,
    description: "שער לאלפים השוויצריים ולאגם למן",
  },
  {
    id: "brussels",
    city: "בריסל",
    cityEn: "Brussels",
    country: "בלגיה",
    airportCode: "BRU",
    imageUrl: "https://picsum.photos/seed/brussels-travel/800/600",
    popular: false,
    description: "וופלים, שוקולד וכיכר הגראנד פלאס",
  },
  {
    id: "copenhagen",
    city: "קופנהגן",
    cityEn: "Copenhagen",
    country: "דנמרק",
    airportCode: "CPH",
    imageUrl: "https://picsum.photos/seed/copenhagen-travel/800/600",
    popular: false,
    description: "עיצוב סקנדינבי, אופניים ונמל טיבולי",
  },
  {
    id: "stockholm",
    city: "שטוקהולם",
    cityEn: "Stockholm",
    country: "שוודיה",
    airportCode: "ARN",
    imageUrl: "https://picsum.photos/seed/stockholm-travel/800/600",
    popular: false,
    description: "פרוסה על פני 14 איים עם עיר עתיקה ציורית",
  },
  {
    id: "oslo",
    city: "אוסלו",
    cityEn: "Oslo",
    country: "נורווגיה",
    airportCode: "OSL",
    imageUrl: "https://picsum.photos/seed/oslo-travel/800/600",
    popular: false,
    description: "פיורדים, טבע וארכיטקטורה מודרנית",
  },
  {
    id: "helsinki",
    city: "הלסינקי",
    cityEn: "Helsinki",
    country: "פינלנד",
    airportCode: "HEL",
    imageUrl: "https://picsum.photos/seed/helsinki-travel/800/600",
    popular: false,
    description: "עיצוב פיני, סאונות וקרבה לטבע",
  },
  {
    id: "warsaw",
    city: "ורשה",
    cityEn: "Warsaw",
    country: "פולין",
    airportCode: "WAW",
    imageUrl: "https://picsum.photos/seed/warsaw-travel/800/600",
    popular: false,
    description: "עיר שקמה מחדש עם היסטוריה מרתקת",
  },
  {
    id: "bucharest",
    city: "בוקרשט",
    cityEn: "Bucharest",
    country: "רומניה",
    airportCode: "OTP",
    imageUrl: "https://picsum.photos/seed/bucharest-travel/800/600",
    popular: false,
    description: "פריז הקטנה של מזרח אירופה",
  },
  {
    id: "sofia",
    city: "סופיה",
    cityEn: "Sofia",
    country: "בולגריה",
    airportCode: "SOF",
    imageUrl: "https://picsum.photos/seed/sofia-travel/800/600",
    popular: false,
    description: "חופשה תקציבית עם הרים ומרחצאות תרמיים",
  },
  {
    id: "dublin",
    city: "דבלין",
    cityEn: "Dublin",
    country: "אירלנד",
    airportCode: "DUB",
    imageUrl: "https://picsum.photos/seed/dublin-travel/800/600",
    popular: false,
    description: "פאבים, מוזיקה חיה וירוק אינסופי",
  },
  {
    id: "nice",
    city: "ניס",
    cityEn: "Nice",
    country: "צרפת",
    airportCode: "NCE",
    imageUrl: "https://picsum.photos/seed/nice-travel/800/600",
    popular: true,
    description: "הריביירה הצרפתית - חופים וטיילת מפורסמת",
  },
  {
    id: "venice",
    city: "ונציה",
    cityEn: "Venice",
    country: "איטליה",
    airportCode: "VCE",
    imageUrl: "https://picsum.photos/seed/venice-travel/800/600",
    popular: true,
    description: "תעלות רומנטיות וגונדולות עתיקות",
  },
  {
    id: "naples",
    city: "נאפולי",
    cityEn: "Naples",
    country: "איטליה",
    airportCode: "NAP",
    imageUrl: "https://picsum.photos/seed/naples-travel/800/600",
    popular: false,
    description: "פיצה אמיתית, פומפיי והחוף האמלפיטני בקרבת מקום",
  },
  {
    id: "florence",
    city: "פירנצה",
    cityEn: "Florence",
    country: "איטליה",
    airportCode: "FLR",
    imageUrl: "https://picsum.photos/seed/florence-travel/800/600",
    popular: false,
    description: "עריסת הרנסאנס עם אמנות ואדריכלות עוצרות נשימה",
  },
  {
    id: "porto",
    city: "פורטו",
    cityEn: "Porto",
    country: "פורטוגל",
    airportCode: "OPO",
    imageUrl: "https://picsum.photos/seed/porto-travel/800/600",
    popular: false,
    description: "יין פורט, גשרים עתיקים ונהר דואורו",
  },
  {
    id: "valencia",
    city: "ולנסיה",
    cityEn: "Valencia",
    country: "ספרד",
    airportCode: "VLC",
    imageUrl: "https://picsum.photos/seed/valencia-travel/800/600",
    popular: false,
    description: "פאייה מקורית, חופים וארכיטקטורה עתידנית",
  },
  {
    id: "palma",
    city: "פלמה דה מיורקה",
    cityEn: "Palma de Mallorca",
    country: "ספרד",
    airportCode: "PMI",
    imageUrl: "https://picsum.photos/seed/palma-travel/800/600",
    popular: true,
    description: "האי הבלארי הפופולרי עם מפרצים כחולים",
  },
  {
    id: "santorini",
    city: "סנטוריני",
    cityEn: "Santorini",
    country: "יוון",
    airportCode: "JTR",
    imageUrl: "https://picsum.photos/seed/santorini-travel/800/600",
    popular: true,
    description: "שקיעות מדהימות ובתים לבנים-כחולים על הצוק",
  },
  {
    id: "mykonos",
    city: "מיקונוס",
    cityEn: "Mykonos",
    country: "יוון",
    airportCode: "JMK",
    imageUrl: "https://picsum.photos/seed/mykonos-travel/800/600",
    popular: true,
    description: "חופים, חיי לילה וטחנות רוח מפורסמות",
  },
  {
    id: "rhodes",
    city: "רודוס",
    cityEn: "Rhodes",
    country: "יוון",
    airportCode: "RHO",
    imageUrl: "https://picsum.photos/seed/rhodes-travel/800/600",
    popular: false,
    description: "עיר עתיקה מוקפת חומות ואבירים",
  },
  {
    id: "crete",
    city: "כרתים",
    cityEn: "Heraklion",
    country: "יוון",
    airportCode: "HER",
    imageUrl: "https://picsum.photos/seed/crete-travel/800/600",
    popular: false,
    description: "האי הגדול ביוון עם חופים וארמון קנוסוס",
  },
  {
    id: "zagreb",
    city: "זאגרב",
    cityEn: "Zagreb",
    country: "קרואטיה",
    airportCode: "ZAG",
    imageUrl: "https://picsum.photos/seed/zagreb-travel/800/600",
    popular: false,
    description: "עיר בירה קסומה עם שער לחופי קרואטיה",
  },
  {
    id: "belgrade",
    city: "בלגרד",
    cityEn: "Belgrade",
    country: "סרביה",
    airportCode: "BEG",
    imageUrl: "https://picsum.photos/seed/belgrade-travel/800/600",
    popular: false,
    description: "חיי לילה תוססים על שפת שני נהרות",
  },
  {
    id: "ljubljana",
    city: "לובליאנה",
    cityEn: "Ljubljana",
    country: "סלובניה",
    airportCode: "LJU",
    imageUrl: "https://picsum.photos/seed/ljubljana-travel/800/600",
    popular: false,
    description: "בירה ירוקה וקטנה עם טירה על הגבעה",
  },
  {
    id: "bratislava",
    city: "ברטיסלבה",
    cityEn: "Bratislava",
    country: "סלובקיה",
    airportCode: "BTS",
    imageUrl: "https://picsum.photos/seed/bratislava-travel/800/600",
    popular: false,
    description: "עיר בירה קומפקטית על גדות הדנובה",
  },
  {
    id: "riga",
    city: "ריגה",
    cityEn: "Riga",
    country: "לטביה",
    airportCode: "RIX",
    imageUrl: "https://picsum.photos/seed/riga-travel/800/600",
    popular: false,
    description: "אדריכלות ארט-נובו והעיר העתיקה של הבלטים",
  },
  {
    id: "tbilisi",
    city: "טביליסי",
    cityEn: "Tbilisi",
    country: "גאורגיה",
    airportCode: "TBS",
    imageUrl: "https://picsum.photos/seed/tbilisi-travel/800/600",
    popular: true,
    description: "יעד חם בשנים האחרונות - הרים, יין ומטבח עשיר",
  },
  {
    id: "yerevan",
    city: "ירואן",
    cityEn: "Yerevan",
    country: "ארמניה",
    airportCode: "EVN",
    imageUrl: "https://picsum.photos/seed/yerevan-travel/800/600",
    popular: false,
    description: "אחת הערים העתיקות בעולם עם נוף להר אררט",
  },
  {
    id: "baku",
    city: "באקו",
    cityEn: "Baku",
    country: "אזרבייג'ן",
    airportCode: "GYD",
    imageUrl: "https://picsum.photos/seed/baku-travel/800/600",
    popular: false,
    description: "עיר עתיקה לצד גורדי שחקים עתידניים",
  },
  {
    id: "tokyo",
    city: "טוקיו",
    cityEn: "Tokyo",
    country: "יפן",
    airportCode: "NRT",
    imageUrl: "https://picsum.photos/seed/tokyo-travel/800/600",
    popular: true,
    description: "עתיד וטכנולוגיה לצד מקדשים ומסורת יפנית",
  },
  {
    id: "seoul",
    city: "סיאול",
    cityEn: "Seoul",
    country: "דרום קוריאה",
    airportCode: "ICN",
    imageUrl: "https://picsum.photos/seed/seoul-travel/800/600",
    popular: false,
    description: "קיי-פופ, אוכל רחוב ופלטים היסטוריים",
  },
  {
    id: "hong-kong",
    city: "הונג קונג",
    cityEn: "Hong Kong",
    country: "הונג קונג",
    airportCode: "HKG",
    imageUrl: "https://picsum.photos/seed/hongkong-travel/800/600",
    popular: false,
    description: "גורדי שחקים, נמל מרהיב ומטבח קנטוני",
  },
  {
    id: "singapore",
    city: "סינגפור",
    cityEn: "Singapore",
    country: "סינגפור",
    airportCode: "SIN",
    imageUrl: "https://picsum.photos/seed/singapore-travel/800/600",
    popular: true,
    description: "עיר-מדינה נקייה ומרשימה עם גני עתיד",
  },
  {
    id: "kuala-lumpur",
    city: "קואלה לומפור",
    cityEn: "Kuala Lumpur",
    country: "מלזיה",
    airportCode: "KUL",
    imageUrl: "https://picsum.photos/seed/kualalumpur-travel/800/600",
    popular: false,
    description: "מגדלי התאומים הפטרונס ומטבח רב-תרבותי",
  },
  {
    id: "bali",
    city: "באלי",
    cityEn: "Bali",
    country: "אינדונזיה",
    airportCode: "DPS",
    imageUrl: "https://picsum.photos/seed/bali-travel/800/600",
    popular: true,
    description: "מקדשים, טראסות אורז וחופים טרופיים",
  },
  {
    id: "phuket",
    city: "פוקט",
    cityEn: "Phuket",
    country: "תאילנד",
    airportCode: "HKT",
    imageUrl: "https://picsum.photos/seed/phuket-travel/800/600",
    popular: true,
    description: "חופים טרופיים ואיים מפורסמים בסביבה",
  },
  {
    id: "colombo",
    city: "קולומבו",
    cityEn: "Colombo",
    country: "סרי לנקה",
    airportCode: "CMB",
    imageUrl: "https://picsum.photos/seed/colombo-travel/800/600",
    popular: false,
    description: "שער לתה, פילים וחופי סרי לנקה",
  },
  {
    id: "delhi",
    city: "דלהי",
    cityEn: "Delhi",
    country: "הודו",
    airportCode: "DEL",
    imageUrl: "https://picsum.photos/seed/delhi-travel/800/600",
    popular: false,
    description: "שער להודו - ארמונות, שווקים וטאג מהאל בקרבת מקום",
  },
  {
    id: "abu-dhabi",
    city: "אבו דאבי",
    cityEn: "Abu Dhabi",
    country: "איחוד האמירויות",
    airportCode: "AUH",
    imageUrl: "https://picsum.photos/seed/abudhabi-travel/800/600",
    popular: false,
    description: "מסגד השייח זאיד ואי יאס עם לוברי אבו דאבי",
  },
  {
    id: "doha",
    city: "דוחה",
    cityEn: "Doha",
    country: "קטאר",
    airportCode: "DOH",
    imageUrl: "https://picsum.photos/seed/doha-travel/800/600",
    popular: false,
    description: "טיילת הקורניש ומוזיאון האמנות האסלאמית",
  },
  {
    id: "amman",
    city: "עמאן",
    cityEn: "Amman",
    country: "ירדן",
    airportCode: "AMM",
    imageUrl: "https://picsum.photos/seed/amman-travel/800/600",
    popular: true,
    description: "שער לפטרה, ואדי רם וים המלח הירדני",
  },
  {
    id: "cairo",
    city: "קהיר",
    cityEn: "Cairo",
    country: "מצרים",
    airportCode: "CAI",
    imageUrl: "https://picsum.photos/seed/cairo-travel/800/600",
    popular: true,
    description: "פירמידות גיזה, המוזיאון המצרי ונהר הנילוס",
  },
  {
    id: "marrakech",
    city: "מרקש",
    cityEn: "Marrakech",
    country: "מרוקו",
    airportCode: "RAK",
    imageUrl: "https://picsum.photos/seed/marrakech-travel/800/600",
    popular: true,
    description: "שווקי מדינה, ריאדים וטעמי מרוקו האותנטיים",
  },
  {
    id: "zanzibar",
    city: "זנזיבר",
    cityEn: "Zanzibar",
    country: "טנזניה",
    airportCode: "ZNZ",
    imageUrl: "https://picsum.photos/seed/zanzibar-travel/800/600",
    popular: false,
    description: "חופים טרופיים ותבלינים באי החלומי",
  },
  {
    id: "mauritius",
    city: "מאוריציוס",
    cityEn: "Mauritius",
    country: "מאוריציוס",
    airportCode: "MRU",
    imageUrl: "https://picsum.photos/seed/mauritius-travel/800/600",
    popular: false,
    description: "אי גן עדן באוקיינוס ההודי עם לגונות טורקיז",
  },
  {
    id: "miami",
    city: "מיאמי",
    cityEn: "Miami",
    country: "ארה\"ב",
    airportCode: "MIA",
    imageUrl: "https://picsum.photos/seed/miami-travel/800/600",
    popular: true,
    description: "חופי סאות' ביץ', אמנות ואר-דקו וחיי לילה",
  },
  {
    id: "los-angeles",
    city: "לוס אנג'לס",
    cityEn: "Los Angeles",
    country: "ארה\"ב",
    airportCode: "LAX",
    imageUrl: "https://picsum.photos/seed/losangeles-travel/800/600",
    popular: false,
    description: "הוליווד, חופים ופארקי שעשועים מפורסמים",
  },
  {
    id: "toronto",
    city: "טורונטו",
    cityEn: "Toronto",
    country: "קנדה",
    airportCode: "YYZ",
    imageUrl: "https://picsum.photos/seed/toronto-travel/800/600",
    popular: false,
    description: "עיר רב-תרבותית עם מגדל CN ומפלי הניאגרה בקרבת מקום",
  },
  {
    id: "cancun",
    city: "קנקון",
    cityEn: "Cancun",
    country: "מקסיקו",
    airportCode: "CUN",
    imageUrl: "https://picsum.photos/seed/cancun-travel/800/600",
    popular: false,
    description: "חופים קריביים לבנים ואתרי מאיה עתיקים",
  },
];

// Domestic (Israel) destinations for hotel-only search
export const DOMESTIC_DESTINATIONS: Destination[] = [
  {
    id: "eilat",
    city: "אילת",
    cityEn: "Eilat",
    country: "ישראל",
    airportCode: "ETM",
    imageUrl: "https://picsum.photos/seed/eilat-travel/800/600",
    popular: true,
    description: "ים סוף, שמש כל השנה ומלונות יוקרה",
  },
  {
    id: "tiberias",
    city: "טבריה",
    cityEn: "Tiberias",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/tiberias-travel/800/600",
    popular: true,
    description: "כנרת, ספא ונופש רגוע בצפון",
  },
  {
    id: "dead-sea",
    city: "ים המלח",
    cityEn: "Dead Sea",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/deadsea-travel/800/600",
    popular: true,
    description: "מרחצאות מינרלים ומלונות ספא ברמה עולמית",
  },
  {
    id: "tel-aviv",
    city: "תל אביב",
    cityEn: "Tel Aviv",
    country: "ישראל",
    airportCode: "TLV",
    imageUrl: "https://picsum.photos/seed/telaviv-travel/800/600",
    popular: true,
    description: "חופים, חיי לילה ומסעדות ברמה עולמית",
  },
  {
    id: "jerusalem",
    city: "ירושלים",
    cityEn: "Jerusalem",
    country: "ישראל",
    airportCode: "",
    imageUrl: "https://picsum.photos/seed/jerusalem-travel/800/600",
    popular: false,
    description: "העיר העתיקה וההיסטוריה בת אלפי השנים",
  },
];

export const ALL_DESTINATIONS = [...DESTINATIONS, ...DOMESTIC_DESTINATIONS];

// English city name for a given IATA code, used for real booking-site deep links.
export function airportCityEn(code: string): string {
  if (code === HOME_AIRPORT) return "Tel Aviv";
  const dest = ALL_DESTINATIONS.find((d) => d.airportCode === code);
  return dest?.cityEn ?? code;
}

export const AIRLINES: { code: string; name: string }[] = [
  { code: "LY", name: "אל על" },
  { code: "IZ", name: "ארקיע" },
  { code: "6H", name: "ישראייר" },
  { code: "W6", name: "וויזאייר" },
  { code: "FR", name: "ראיינאייר" },
  { code: "TK", name: "טורקיש איירליינס" },
  { code: "LH", name: "לופטהנזה" },
  { code: "AF", name: "אייר פראנס" },
  { code: "BA", name: "בריטיש איירווייז" },
  { code: "EK", name: "אמירייטס" },
];
